apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp-deployment
  namespace: secrets
  labels:
    app: goapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
      - name: web
        image: acidicmercury8/goapp:v0.2
        ports:
        - containerPort: 8080
        env:
        - name: SECRETENV
          valueFrom:
            secretKeyRef:
              name: first-secret
              key: password
