piVersion: v1
kind: ConfigMap
metadata:
  name: cm-with-volume
  namespace: data-storage
data:
  colorgood: purple
  colorbad: yellow
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goapp
  template:
    spec:
      containers:
      - name: web
        image: acidicmercury8/goapp:v0.2
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: cm-volume
          mountPath: "/etc/ssl/certs/"
          readOnly: true
      volumes:
        - name: cm-volume
          configMap:
            name: test-config
