name:                primitivecompiler
version:             0.1.0.0
github:              "acidicMercury8/compiler-workshop-haskell"
license:             MIT
author:              "acidicMercury8"
maintainer:          "acidicmercury8@outlook.com"
copyright:           "2022 acidicMercury8"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/acidicMercury8/compiler-workshop-haskell#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - parsec

executables:
  primitivecompiler-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - primitivecompiler

tests:
  primitivecompiler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - primitivecompiler
