apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: livenesstest-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      api: loremapi
  template:
    metadata:
      labels:
        api: loremapi
    spec:
      containers:
      - name: liveness-webapi
        image: acidicmercury8/livenesstest
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: livenesstest-replicaset2
spec:
  replicas: 1
  selector:
    matchLabels:
      api: loremapi
  template:
    metadata:
      labels:
        api: loremapi
    spec:
      containers:
      - name: liveness-webapi
        image: acidicmercury8/livenesstest:2
        livenessProbe:
          httpGet:
            path: /api/health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: liveness-loadbalancer
spec:
  type: LoadBalancer
  selector:
    api: loremapi
  ports:
  - port: 8080
    targetPort: 80
---
