version: '3.4'

services:
  livenesstest:
    container_name: livenesstest
    image: acidicmercury8/livenesstest:latest
    restart: always
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_URLS=https://+:8001;http://+:8000
      - ASPNETCORE_HTTPS_PORT=8001
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8000:5001"
      - "8001:5003"
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/
