name: Bug report
description: Create a report to help me improve
labels: bug
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: >
        A clear and concise description of what the bug is
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: >
        A clear and concise description of what you expected to happen
