kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ivanov_aa-reader-pods
  namespace: rbac
subjects:
- kind: ServiceAccount
  name: demo-sa
  namespace: rbac
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
