services:
  redis:
    image: redis
    labels:
      - ru.acidicmercury8.compose.app=task-manager
    ports:
      - 6379:6379

  redis-populate:
    image: redis
    depends_on:
      - redis
    entrypoint: ["/redis-populate.sh", "/redis-populate.txt"]
    env_file:
      - ./env.redis-populate
    volumes:
      - ./redis-populate.txt:/redis-populate.txt
      - ./redis-populate.sh:/redis-populate.sh

  task-manager:
    build: .
    image: task-manager:0.1
    labels:
      - ru.acidicmercury8.compose.app=task-manager
    depends_on:
      - redis
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis:6379
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 5s
