name: 'Build monoid folding test'

on:
  push:
    branches:
      - '**'
    paths:
      - 'monoid-folding-test/**'
      - '.github/workflows/build-monoid-folding-test.yml'
  pull_request:
    branches:
      - '**'
    paths:
      - 'monoid-folding-test/**'
      - '.github/workflows/build-monoid-folding-test.yml'

defaults:
  run:
    working-directory: monoid-folding-test

jobs:
  build:
    name: 'Building'

    strategy:
      matrix:
        system: [ windows-2022 ]
        config: [ Debug, Release ]

    runs-on: ${{ matrix.system }}

    env:
      Solution: MonoidFoldingTest.sln

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Install dependencies
        run: |
          dotnet restore $env:Solution

      - name: Build solution
        run: |
          dotnet build $env:Solution -p:Configuration=${{ matrix.config }} --no-restore

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: monoid-folding-test-${{ matrix.config }}-${{ github.sha }}
          path: monoid-folding-test/bin/${{ matrix.config }}/
