name: 'Build AST processing application'

on:
  push:
    branches:
      - '**'
    paths:
      - 'ast-processing-app/**'
      - '.github/workflows/build-ast-processing-app.yml'
  pull_request:
    branches:
      - '**'
    paths:
      - 'ast-processing-app/**'
      - '.github/workflows/build-ast-processing-app.yml'

permissions:
  contents: read

jobs:
  build-all:
    name: 'Building'

    strategy:
      matrix:
        system: [ ubuntu-latest ]
        ghc: [ '9.0.2' ]
        stack: [ '2.7.5' ]

    runs-on: ${{ matrix.system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          stack-version: ${{ matrix.stack }}

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-${{ hashFiles('ast-processing-app/stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-

      - name: Install dependencies
        run: |
          stack build --dependencies-only
        working-directory: ast-processing-app

      - name: Build application
        run: |
          stack build
        working-directory: ast-processing-app
