name: 'Build ML.NET samples'

on:
  push:
    branches:
      - '**'
    paths:
      - 'mldotnet-samples/**'
      - '.github/workflows/build-mldotnet-samples.yml'
  pull_request:
    branches:
      - '**'
    paths:
      - 'mldotnet-samples/**'
      - '.github/workflows/build-mldotnet-samples.yml'

defaults:
  run:
    working-directory: mldotnet-samples

jobs:
  build:
    name: 'Building'

    strategy:
      matrix:
        system: [ windows-2022 ]
        config: [ Debug, Release ]

    runs-on: ${{ matrix.system }}

    env:
      Solution: ML.NET.sln

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Install dependencies
        run: |
          dotnet restore $env:Solution

      - name: Build solution
        run: |
          dotnet build $env:Solution -p:Configuration=${{ matrix.config }} --no-restore

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mldotnet-samples-${{ matrix.config }}-${{ github.sha }}
          path: mldotnet-samples/bin/${{ matrix.config }}/
