name: 'Build AST processing application'

on:
  push:
    branches:
      - '**'
    paths:
      - 'ast-processing-app/**'
      - '.github/workflows/build-ast-processing-app.yml'
  pull_request:
    branches:
      - '**'
    paths:
      - 'ast-processing-app/**'
      - '.github/workflows/build-ast-processing-app.yml'

jobs:
  build-stack:
    name: 'Building with Stack'

    strategy:
      matrix:
        system: [ ubuntu-20.04, ubuntu-22.04 ]
        ghc: [ '9.0.2' ]
        stack: [ '2.7.5' ]

    runs-on: ${{ matrix.system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          stack-version: ${{ matrix.stack }}

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-ghc-${{ matrix.ghc-version }}-stack
          restore-keys: |
            ${{ runner.os }}-ghc-${{ matrix.ghc-version }}-stack

      - name: Install dependencies
        run: |
          stack build --dependencies-only
        working-directory: ast-processing-app

      - name: Build application
        run: |
          stack build
          stack install --local-bin-path out/
        working-directory: ast-processing-app

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ast-processing-app-${{ matrix.system }}-${{ matrix.ghc }}-${{ matrix.stack }}
          path: ast-processing-app/out/
